apiVersion: apps/v1
kind: Deployment
metadata:
        name: time-deployment
        labels:
                role:
                        app
spec:
        replicas: 2
        selector:
                matchLabels:
                        role: app
        template:
                metadata:
                        labels:
                                role: app
                spec:
                        containers:
                                - name: app
                                  image: go-test:latest
                                  imagePullPolicy: Never
                                  resources:
                                          requests:
                                                  cpu: 10m
